### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by TechnikEmpire** [yonixw/HttpsFilter#1]
Is this a custom Mobicip client or something? Saw you forked my filtering engine repo so I was just curious.

**Comment by yonixw** [comment]
Well not really, I used Mobicip because it gives free VPN with AI to detect mature content inside pages. But the VPN performance was real bad so I made a proxy (without decrypting HTTPS) for video sites like Twitch, YouTube etc. And intended to use Mobicip for everything else. 

But after further use of the VPN, I just couldn't handle the performance. So I'm thinking about making something myself ... of course using WinDivert cause I'm on windows. Your CitadelCore proj worked out of the box so I'm thinking of using it. All for personal use (your readme made me lol) ... Still looking for Andorid solution also but all I have found without root is VPN solutions ....

**Comment by TechnikEmpire** [comment]
haha I'm glad it made you lol. I was just curious. I don't care if it's for commercial use (that's why I did MPL license). My ReadMe is aimed at a couple companies that got all crybaby on me when they realized I wasn't going to sit around building and running their company for them.

Anyway you should check out:

https://github.com/TechnikEmpire/DistillNET

https://github.com/TechnikEmpire/WinDivertSharp

https://github.com/alexreinert/ARSoft.Tools.Net

https://github.com/falahati/WindowsFirewallHelper

https://github.com/TechnikEmpire/HttpFilteringEngine

etc etc. 

WinDivert + local filtering proxy is about as fast as it gets. However, if you really just want to block domains, you could just peek SNI data on encrypted connections, or peek the HTTP GET on new outbound connections and determine at the packet level if you want to drop the connections or not. That would be about as fast as you possibly can get without writing a custom driver, because there'd be no overhead of intercepting and processing the connections.

All the best with your project.

**Comment by TechnikEmpire** [comment]
Oh I glossed over android. You have to fork a de-google chrome browser abs build in filtering. I've tried writing local filtering VPN solutions and you're fighting against Google. Built in certificate pinning for apps is one example of how Google works against programs like this.

A custom filtering browser + app locker is as good as it gets sadly.

**Comment by yonixw** [comment]
Thnx I Will look into it
